version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - iot-net
    restart: unless-stopped

  mqtt-simulator:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-simulator
    depends_on:
      - mqtt-broker
    command: >
      sh -c "while true; do \
        mosquitto_pub -h mqtt-broker -p 1883 -t sensors/temp -m \"{\\\"temperature\\\":22.5,\\\"battery\\\":92}\"; \
        mosquitto_pub -h mqtt-broker -p 1883 -t sensors/humidity -m \"{\\\"humidity\\\":48.3,\\\"battery\\\":88}\"; \
        mosquitto_pub -h mqtt-broker -p 1883 -t lights/lamp1/state -m \"{\\\"on\\\":true,\\\"level\\\":56}\"; \
        sleep 5; \
      done"
    networks:
      - iot-net
    restart: unless-stopped

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    depends_on:
      - mqtt-broker
    networks:
      - iot-net
    volumes:
      - ./mqtt-explorer-data:/data
    restart: unless-stopped

  zigbee-mock:
    build: ./zigbee-mock
    container_name: zigbee-mock
    ports:
      - "3000:3000"
    networks:
      - iot-net
    restart: unless-stopped

  openhab:
    image: openhab/openhab:4.3.0-debian
    container_name: openhab
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mqtt-broker
      - zigbee-mock
    networks:
      - iot-net
    volumes:
      - ./openhab_conf:/openhab/conf
      - ./openhab-data/userdata:/openhab/userdata
      - ./openhab-data/addons:/openhab/addons
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Kiev
    restart: unless-stopped

networks:
  iot-net:
    driver: bridge

